stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "myapp"
  IMAGE_TAG: "$CI_COMMIT_SHA"

# Test stage
test_job:
  stage: test
  image: python:3.9-slim
  script:
    - pip install flake8 pytest
    - flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - python app.py
  only:
    - merge_requests
    - main
    - develop

# Build stage
build_job:
  stage: build
  image: quay.io/podman/stable
  services:
    - docker:dind
  script:
    - podman build -t $IMAGE_NAME:$IMAGE_TAG .
    - podman build -t $IMAGE_NAME:latest .
    - podman run --rm $IMAGE_NAME:latest
    - podman save $IMAGE_NAME:latest -o myapp-image.tar
  artifacts:
    paths:
      - myapp-image.tar
    expire_in: 1 day
  only:
    - main
    - develop

# Deploy to staging
deploy_staging:
  stage: deploy
  image: quay.io/podman/stable
  script:
    - podman load -i myapp-image.tar
    - podman run -d --name myapp-staging -p 8081:80 $IMAGE_NAME:latest
    - echo "Deployed to staging environment"
  environment:
    name: staging
    url: http://staging.example.com:8081
  only:
    - develop

# Deploy to production
deploy_production:
  stage: deploy
  image: quay.io/podman/stable
  script:
    - podman load -i myapp-image.tar
    - podman run -d --name myapp-prod -p 8080:80 $IMAGE_NAME:latest
    - echo "Deployed to production environment"
  environment:
    name: production
    url: http://production.example.com:8080
  when: manual
  only:
    - main